### ISSUE TITLE
Clock.py - Add additional option to announce on the quarter-hour

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#16] opened 2020-04-27 11:12 UTC
Many chiming clocks announce on the quarter-hour (0-15-30-45). It would be nice to have an option that does that.

'Continuous' can be a bit too much, while 'Hour' isn't often enough in some cases.

Something like `Quarter` seems reasonable.

**Comment by AESilky** [comment] 2020-04-27 11:17
Maybe also except a number to announce at that minute interval. For example `10` would announce every ten minutes.

**Comment by pwdirks** [comment] 2020-04-30 19:13
The format of the announcement message now is "The time is eleven oclock" followed, after a brief pause, by 11 long dashes.  How should :15, :30, and :45 be announced, or arbitrary times?  "The time is eleven ten"?  "The time is a quarter past eleven" and "The time is half past eleven"?  Or simply "The time is 11:40" for any time other than whole hours?  Or a mix, with the quarter hours announced textually and other times numerically?

**Comment by leskerr** [comment] 2020-04-30 20:14
I suppose if the user requests specific intervals (e.g. every 10, 15, 30, 60, or whatever) then the announcement at the top of the hour could be just like all the others (e.g. 'The time is 3:00'). If no interval is specified, then the 'cuckoo clock' format of 'The time is 3 oclock    <dash> <dash> <dash>' would apply.

By the way, the colon in the time is not a recognized character in pykob's code sender. This has a happy consequence here, because unrecognized characters are sent as an additional half space in the sent Morse. This means there's a very slight pause between the hour and the minutes in the time announcement, just the way a human operator would subconsciously send it.

In a similar vein (not that it applies here), the apostrophe is also an unrecognized character. So contractions like "isn't" and possessives like "Sam's" are sent with a slight pause where the apostrophe would be, again like a human operator would tend to do it. The pause is almost imperceptible unless you're consciously listening for it.

And just to be clear, this issue (#16) applies to Clock.py, not Time.py. Time.py sends time signals in a specifc format used by the Naval Observatory back in the day. These time signals were relayed to all railroad offices once a day at a particular time, so that standard clocks could be synchronized and kept accurate. This synchronization was done semiautomatically, and is an interesting topic in its own right.

**Comment by AESilky** [comment] 2020-05-02 08:23
I am fine with either approach:
1. The time is eleven o'clock, The time is 11:05, The time is 11:10, The time is quarter past eleven.
2. The time is eleven o'clock, The time is 11:05, The time is 11:10, The time is 11:15.
3. The time is eleven o'clock (if no option is used). The time is 11:00, The time is 11:05, The time is 11:10, The time is 11:15.

I kind of like #1 as a learning application because it lets me get a lot of different (yet expected) messages (one every minute, every two minutes, every five minutes, etc. as I want). So I get more than one an hour to help me learn, they are different (including some different text), yet I know what to expect (rather than unknown information as I get if I listen to a news feed).

**Comment by pwdirks** [comment] 2020-05-03 01:17
I decided to go all out and implement approach #1: midnight/noon, quarter past/quarter of, half past, xxx o'clock L L L L as appropriate.

Pull request #29 is awaiting your comments on the changes.

**Comment by AESilky** [comment] 2020-05-04 07:28
I find that the `-a`/`--sound` command line options in `clock.py` do not accept lower case 'on'/'off' as valid values, but `configure.py` (the global configuration application) accepts any case  (upper/lower/mixed) as well as accepting other values to enable/disable sound output ('yes/no', 'true/false').

All applications using the 'standard' options should accept the standard values.

**Comment by AESilky** [comment] 2020-05-04 08:09
I tried running this with `--interval 1` and I get the initial announcement but I waited a number of minutes and didn't get any further announcements.

Here is a sequence of commands where I get the initial announcement, but not the 1 minute announcements that I requested, or even the 'top of the hour' announcement. In the commands below, I ran the next command as soon as I did ^C to exit the previous one. You can see that I didn't get any announcements after the initial one, including the top of the hour.

```
Eds-Macbook:PyKOB esilky$ python3 clock.py --interval 1 -t --sound ON
2020-05-04 00:46:35 Starting Clock
> The time is 0:46
^C
Eds-Macbook:PyKOB esilky$ python3 clock.py --interval 1 -t --sound ON
2020-05-04 00:50:34 Starting Clock
> The time is 0:50
^C
Eds-Macbook:PyKOB esilky$ python3 clock.py --interval 1 -t --sound ON
2020-05-04 01:02:48 Starting Clock
> The time is 1:02
```

**Comment by pwdirks** [comment] 2020-05-04 16:33
I run it with "-i 15" without issue.  I think an interval of '1' probably messes up some rounding, since "n % 1" == 0 for any <n>.  Try --interval 5?  Or at least "--interval 2"?

I think this warrants a check on the -i value to make sure it's >1, or a fix to announce every minute properly by guarding against trying to round with an interval value of 1.

**Comment by pwdirks** [comment] 2020-05-04 17:37
Actually - the time interval (which SHOULD be checked to make sure it's AT LEAST 1) works for --interval 1:

> $ python3 Clock.py -b 0 -e 2400 -i 1 -s 18 -a OFF -t
> 2020-05-04 10:26:24 Starting Clock
> > The time is 10:26
> > The time is 10:27
> > The time is 10:28

LOL - I just realized your problem: like the original, the program by default announces only between 0900 and 2230 (actually, the original last announced at 2200 - I wanted to have a case for 'minutes'; I'll fix it back up).  You're doing your testing around 1AM and the first step your clock goes through is to sleep until a more decent hour :-)  You have to specify "-b 0" to start at midnight, or "-e 2400" to go all the way to midnight.

I believe this is working as designed but I'll check in a fix to validate that interval is >= 1 and restore the default end time of 10PM.

**Comment by AESilky** [comment] 2020-05-04 18:34
Ah, that makes sense. I do a lot of my SW work late/early so I'll keep that
in mind.

**Comment by pwdirks** [comment] 2020-05-04 22:21
This should be resolved with the merge of pwd-16-clock-announcement-interval in pull request #32.

**Closed by pwdirks** 2020-05-04 22:21 UTC

**Comment by pwdirks** [comment] 2020-05-10 23:48
FWIW, here's a full 24-hour's worth of announcements, from noon to noon the next day:

> The time is noon     L L L L L L L L L L L L 
> The time is a quarter past twelve
> The time is half past twelve
> The time is a quarter to one
> The time is one o'clock     L 
> The time is a quarter past one
> The time is half past one
> The time is a quarter to two
> The time is two o'clock     L L 
> The time is a quarter past two
> The time is half past two
> The time is a quarter to three
> The time is three o'clock     L L L 
> The time is a quarter past three
> The time is half past three
> The time is a quarter to four
> The time is four o'clock     L L L L 
> The time is a quarter past four
> The time is half past four
> The time is a quarter to five
> The time is five o'clock     L L L L L 
> The time is a quarter past five
> The time is half past five
> The time is a quarter to six
> The time is six o'clock     L L L L L L 
> The time is a quarter past six
> The time is half past six
> The time is a quarter to seven
> The time is seven o'clock     L L L L L L L 
> The time is a quarter past seven
> The time is half past seven
> The time is a quarter to eight
> The time is eight o'clock     L L L L L L L L 
> The time is a quarter past eight
> The time is half past eight
> The time is a quarter to nine
> The time is nine o'clock     L L L L L L L L L 
> The time is a quarter past nine
> The time is half past nine
> The time is a quarter to ten
> The time is ten o'clock     L L L L L L L L L L 
> The time is a quarter past ten
> The time is half past ten
> The time is a quarter to eleven
> The time is eleven o'clock     L L L L L L L L L L L 
> The time is a quarter past eleven
> The time is half past eleven
> The time is a quarter to twelve
> The time is midnight
> The time is a quarter past twelve
> The time is half past twelve
> The time is a quarter to one
> The time is one o'clock     L 
> The time is a quarter past one
> The time is half past one
> The time is a quarter to two
> The time is two o'clock     L L 
> The time is a quarter past two
> The time is half past two
> The time is a quarter to three
> The time is three o'clock     L L L 
> The time is a quarter past three
> The time is half past three
> The time is a quarter to four
> The time is four o'clock     L L L L 
> The time is a quarter past four
> The time is half past four
> The time is a quarter to five
> The time is five o'clock     L L L L L 
> The time is a quarter past five
> The time is half past five
> The time is a quarter to six
> The time is six o'clock     L L L L L L 
> The time is a quarter past six
> The time is half past six
> The time is a quarter to seven
> The time is seven o'clock     L L L L L L L 
> The time is a quarter past seven
> The time is half past seven
> The time is a quarter to eight
> The time is eight o'clock     L L L L L L L L 
> The time is a quarter past eight
> The time is half past eight
> The time is a quarter to nine
> The time is nine o'clock     L L L L L L L L L 
> The time is a quarter past nine
> The time is half past nine
> The time is a quarter to ten
> The time is ten o'clock     L L L L L L L L L L 
> The time is a quarter past ten
> The time is half past ten
> The time is a quarter to eleven
> The time is eleven o'clock     L L L L L L L L L L L 
> The time is a quarter past eleven
> The time is half past eleven
> The time is a quarter to twelve
> The time is noon     L L L L L L L L L L L L
