### ISSUE TITLE
Implement MKOB's station list window

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#77] opened 2020-06-21 23:10 UTC
This excerpt from the MorseKOB 2.5 tutorial describes the expected behavior. It facilitates round table discussions with multiple operators, such as the nets that take place regularly on wire 11.

> Within 10 seconds after connecting, in the text box in the upper right part of the KOB window you’ll see a list of the IDs for everyone connected to the same wire that you’re on. Whenever someone transmits, their ID is moved to the bottom of the list, so the station at the top of the list is the one that has waited the longest since their last transmission. About 60 seconds after a user disconnects from the wire, their ID is removed from the list.

**Comment by AESilky** [comment] 2020-06-22 06:17
I believe this is a duplicate of #54.

@leskerr is it okay if I move your information to #54 and close this issue as a duplicate?

**Comment by leskerr** [comment] 2020-06-22 06:46
> I believe this is a duplicate of #54.
> 
> @leskerr is it okay if I move the information you put in the description into #54 and close this issue as a duplicate?

Yes, please do that. Sorry for being so clumsy...

**Comment by AESilky** [comment] 2020-06-22 07:17
> 
> > Yes, please do that. Sorry for being so clumsy...

No problem. Not 'clumsy' at all. Better to create an issue when you find/think of it, and then have it be merged to an earlier issue as a duplicate, then to have it not be recorded.

**Comment by AESilky** [comment] 2020-06-22 07:23
Copied details from the MorseKOB 2.5 Tutorial provided by @leskerr to issue #54.
Closing this issue as a duplicate of #54.

**Closed** 2020-06-23 02:00 UTC
Labels: MKOB
