### ISSUE TITLE
Station list duplication

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#109] opened 2020-07-14 14:52 UTC
Very occasionally, all the lines of the station ID list get duplicated in the display. The problem resolves itself quickly, but it is a distraction.

**Comment by AESilky** [comment] 2020-10-19 07:52
Looking at the code and how it can be called (from tracing it while adding the station list update in the play-recording functionality), I think the brief duplication might be caused by a threading condition from `refresh_stations->display_station_list` from the 'keep-alive' thread and `new_sender->display_station_list` from the 'data-read' thread.

Because `display_station_list` checks and purges 'dead' stations, thereby regenerating the list, if it is called by two threads at the same time, I believe it might cause a brief duplication (or partial duplication) of the displayed list.

This condition is very hard to test for. My approach is to put a thread lock on this method. We can then monitor multi-station communications looking for the duplication to occur.

After the change - and a few 'Wire 11' sessions (watching for this issue to occur) that we don't see the duplication occur, I would like to close the issue. We can reopen it if we see it later.

**Comment by leskerr** [comment] 2020-10-19 07:58
@AESilky I knew you'd figure it out. I'll try it on the next wire 11 session.

**Comment by AESilky** [comment] 2020-10-19 09:27
I made the change and did a quick test (just to make sure it didn't seem to break anything) and went ahead and pushed/merged it to master.

As Einstein indicated... all the testing in the world can't prove it's fixed, but one test can prove it's not! :-)
Let's test it on Wire 11 a couple times and see if it occurs (or not).

**Comment by AESilky** [comment] 2020-10-19 09:33
BTW - I noticed the 'station list duplication' twice during the last wire-11 session I was on. They were very brief, but noticeable. Hopefully, this will fix it.

**Comment by AESilky** [comment] 2020-10-30 07:38
I believe that adding the RLock resolved this problem - however, I think it might have introduced Issue #166 . I will look into multi-threading and tkintr to make sure UI updates and being done correctly when triggered by threads other than 'main'.

**Comment by AESilky** [comment] 2020-12-02 23:56
I believe this is fixed.

**Closed by AESilky** 2020-12-02 23:56 UTC
Labels: MKOB, bug

**Comment by leskerr** [comment] 2020-12-03 00:41
I agree that this has been fixed. I haven't seen the problem for a long time.
