### ISSUE TITLE
MKOB sometimes locks up when disconnecting from wire

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#166] opened 2020-10-29 23:05 UTC
Several times lately the program has become unresponsive while I've been using it. When this happens, the only recourse is to force a hard shutdown. This is with Windows, and I believe it has always happened when I've tried to disconnect from the wire while a transmission is in progress.

I've tried unsuccessfully to force it to happen by repeatedly connecting and disconnecting. If it happens again, I'll log the occurrence here. I encourage others to do the same, so we track how persistent the problem is.

**Comment by AESilky** [comment] 2020-11-01 07:37
I was trying to test/force this by repeatedly connecting/disconnecting from Wire-107. After ~10 connect/disconnect actions the GUI locked up. I will work with this process and try to track down the cause.

**Comment by AESilky** [comment] 2020-11-01 09:11
I think the problem might be caused by multiple threads updating the GUI. There was an issue reported for the Station List occasionally duplicating. I put in a lock (RLock) to protect multiple updates - but that was (probably) neive.

The tkinter GUI framework (like the majority of GUI libraries) is 'single-threaded'. What that means is that it only supports GUI interface operations from one thread at a time. Since it's not really known when the Main GUI thread might update a UI component, the general pattern is to make sure that only the Main GUI thread ever updates the GUI components.

In debugging, I've found that a number of threads are updating the GUI components. The most common component to be updated by different threads is the Station List. There are other GUI components that are updated by different threads, but they happen much less frequently. That only helps the problem because it is much less likely to happen.

I believe the fix to this is to make sure that only the Main GUI thread makes changes to the GUI components.

**Comment by leskerr** [comment] 2020-11-01 09:17
Thanks for figuring this out! I wish I had known about this from the beginning. I hope it's not too difficult to restructure things. I'd do it myself if I knew how. Maybe it's a good time for me to learn.

**Comment by AESilky** [comment] 2020-11-01 09:37
Well, we'll see...

I haven't done tons of GUI work, but when I have (WPF, WinForms, Swing, Autodesk-ACAD and Revit) I have been hit by the single-thread update restriction while trying to run multiple threads for operations within the application.

First, I'll work on the Station List - as that is the GUI component that is most frequently updated by different threads. The lock I added is probably what is causing the lockups. However, without the lock we get the occasional (distracting) list duplication.
I will try to make this work well with a pattern to allow the main thread to perform the update from data provided by the internet or recorder-playback thread.

**Comment by AESilky** [comment] 2020-11-02 06:31
Found this and it goes along with the guidelines I've heard (and used) for quite a few years with other GUI frameworks.
https://mail.python.org/pipermail/python-list/2003-December/197985.html

**Comment by leskerr** [comment] 2020-11-03 05:42
@AESilky While you're working on this issue, could you try removing this line from `MKOB\kobkeyboard.py`:

```
time.sleep(1)  # wait for kobwindows to initialize on startup
```

I don't think it's necessary anymore.

**Comment by AESilky** [comment] 2020-11-03 08:27
Removed. Thoughts on how to test?

**Comment by leskerr** [comment] 2020-11-03 17:09
Time will tell. The program used to sometimes fail on startup. I don't have the error message handy, but it mostly got better after I put in that delay. It happened more often with Don Reser's computer than mine.

**Comment by AESilky** [comment] 2020-11-03 18:53
The change I made in kobmain to keep the code from running until everything is initialized might fix this, so I'll remove it in what I am doing with the threading change.

**Comment by leskerr** [comment] 2020-11-10 23:47
`kobkeyboard.py`  creates its own background thread for monitoring the state of the sender window. This thread interacts directly with `kobwindow.txtKeyboard`, the GUI widget for the sender window. Is this a problem?

**Comment by AESilky** [comment] 2020-11-11 00:16
I'll put that on my list to convert to use event-messages.

**Comment by leskerr** [comment] 2020-11-11 00:27
Thanks! It looks like it might be a bit ugly...

**Comment by AESilky** [comment] 2020-11-11 18:06
Planning to join wire-11 tonight to test (un-committed) changes I've made.
They don't include any sender changes, but I think fix other issues.

**Comment by leskerr** [comment] 2020-11-11 19:26
I'll be there too, testing some changes of my own relating to issue #159.

**Comment by AESilky** [comment] 2020-11-16 08:07
Changing access to the MKOB GUI widgets from the different MKOB threads to use tk messages rather than direct modifications seems to have fixed this.

**Closed by AESilky** 2020-11-16 08:07 UTC
Labels: MKOB, bug
